
title: Dessert or Not? A Recipe for Classification
description: by Minyoung Kim and Tanisha Kumar

remote_theme: tuur29/pages-themes-cayman

#remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

sass:
  style: compressed

include:
  - assets/css/style.scss

color:
  header: "#FFFFFF"
  gradient_left: "#EE0A67"
  gradient_right: "#FEA1BE"