remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
    values:
      layout: page  # important fix here!

include:
  - assets/css/style.css
