remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

sass:
  style: compressed

include:
  - assets/css/style.scss

color:
  header: "#000"
  gradient_left: "#d57ad5"
  gradient_right: "#ffb6c1"